version: '3.7'
services:
  database:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goodfood
    ports:
      - "8001:5432"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    command: postgres -c listen_addresses='*'

  redis:
    image: redis:6
    command: redis-server
    ports:
      - "6379:6379"

  server:
    build: .
    depends_on:
      - database
      - redis
    ports:
      - "8080:8080"
    environment:
      DEBUG: '0'
      REDIS_URL: "redis:6379"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/goodfood"

volumes:
  data:
